drop table if exists bookmarks;
create table bookmarks(
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  description text,
  rating integer
);

insert into bookmarks (title,url,description,rating)
values
('title1','url','desc1','2'),
('title2','url','desc2','4'),
('title3','url','desc3','2'),
('title4','url','desc4','5');